### ISSUE TITLE
Reexport imap_proto

### ISSUE THREAD

**Issue by netvl** [async-email/async-imap#20]
Currently imap_proto has a git dependency, which is different, although with the same version, from the one on crates.io. This makes it inconvenient to use the library, because in-project manifest must have a matching the git dependency, because async-imap has types from imap_proto in its public API and can't sensibly be used without it.

I believe that the most idiomatic way would be to re-export the entire imap_proto crate, so there will be no need for the downstream users to import a correct version of it.

**Comment by dignifiedquire** [comment]
Great idea, fixed in latest `master`
