### ISSUE TITLE
unilateral server data responses are not processed at every response.

### ISSUE THREAD

**Issue by Sergey-Kitov** [async-email/async-imap#4]
Unilateral server data responses are responses that can come at any time, so they need to be processed every time response is received. This is also an issue with original rust-imap project.
See https://tools.ietf.org/html/rfc3501 section 7. Server Responses

**Comment by hpk42** [comment]
Could this also lead to an issue that when we start IDLE that we get such responses but we don't properly parse them?  Do you have a suggestion on how unlitateral server data responses should be handled in practise?   As far as i understand, at least Delta Chat currently does not issue multiple tagged client commands, but sequentially waits after issuing one.

**Comment by dignifiedquire** [comment]
should be fixed in `master` @Sergey-Kitov please take a look and reopen if there are still missing areas
