### ISSUE TITLE
Add per-command read/write timeout

### ISSUE THREAD

**Issue by link2xt** [async-email/async-imap#63]
`async-smtp` has a per-connection `timeout` setting that limits how long we wait until we receive a command response:
https://github.com/async-email/async-smtp/blob/da7e8d407cb4e37fdf2aa7e0bd5d402a263de2df/src/smtp/smtp_client.rs#L218

But `async-imap` currently uses timeout only for the `IDLE` command. This may cause IMAP client getting stuck forever trying to read the response if connection is lost (we suspended our machine and NAT has forgot about the connection, for example). This is very likely a cause for this problem of IMAP task getting stuck forever in Delta Chat:
https://github.com/deltachat/deltachat-android/issues/2400#issuecomment-1332394279

The simplest way is to do like `async-smtp` and have a 60-second timeout for each read and for each write call.

**Comment by hpk42** [comment]
seems it worked. if not please re-open.
